server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: jdk11-example
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.123:3307/nbw?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    ######################################################### hikari datasource 配置
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1